import { chromium, devices } from "playwright";
const out = process.env.SHOTS_DIR;
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--enable-gpu", "--use-angle=metal", "--ignore-gpu-blocklist"] });
const ctx = await browser.newContext({ ...devices["iPhone 14"] });
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
await cdp.send("WebAuthn.enable");
await cdp.send("WebAuthn.addVirtualAuthenticator", { options: { protocol: "ctap2", ctap2Version: "ctap2_1", transport: "internal", hasResidentKey: true, hasUserVerification: true, isUserVerified: true, hasPrf: true, automaticPresenceSimulation: true } });
page.on("pageerror", (e) => console.log("pageerror:", e.message.slice(0, 300)));
await page.goto("http://localhost:3000");
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/m-1-landing.png` });
await page.getByRole("button", { name: "Play now", exact: true }).tap();
await page.getByText("You're in.").waitFor({ timeout: 90000 });
await page.waitForFunction(() => !document.querySelector(".Toastify__toast--loading"));
await page.waitForTimeout(3500);
await page.screenshot({ path: `${out}/m-2-lobby.png`, fullPage: true });
await page.getByRole("button", { name: "Create Game", exact: true }).tap();
await page.waitForURL(/game=\d+/, { timeout: 90000 });
await page.waitForFunction(() => document.querySelector("canvas") && !document.body.innerText.includes("Mustering"), null, { timeout: 90000 });
await page.waitForTimeout(4500);
await page.screenshot({ path: `${out}/m-3-game.png`, fullPage: true });
console.log("overflow-x px:", await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth));
await page.getByRole("button", { name: "Cancel & Refund" }).tap();
await page.getByText("cancelled and refunded").waitFor({ timeout: 90000 });
console.log("game cancelled and refunded");
await browser.close();
