// Writes the compiled DegenChess ABI to src/contracts/abi.ts (typed `as const` for wagmi/viem).
// Run after changing the contract: `npm run abi`
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const out = path.join(root, "src/contracts/abi.ts");
const read = (name, file) =>
  JSON.parse(fs.readFileSync(path.join(root, `artifacts/contracts/${file}/${name}.json`), "utf8")).abi;

const erc20 = [
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function mint(address,uint256)", // MockUSD only (testnet/local)
];

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by scripts/export-abi.js - do not edit by hand.
import { parseAbi } from "viem";

export const degenChessAbi = ${JSON.stringify(read("DegenChess", "DegenChess.sol"), null, 2)} as const;

export const playerNamesAbi = ${JSON.stringify(read("PlayerNames", "PlayerNames.sol"), null, 2)} as const;

export const erc20Abi = parseAbi(${JSON.stringify(erc20, null, 2)});
`
);
console.log("wrote", path.relative(root, out));
